### PR TITLE
Sync Report screen with wrong data when come back from the background - FIXED

### LINKED ISSUE #254: Sync Report screen with wrong data when come back from the background
Wrong number of blocks synced.

5 batches -> 296 blocks (have to be from 500 to 599 blocks)

Screenshot_2023-03-15-07-48-32-24

### PR DESCRIPTION
**Pull request by juanky201271**
Finally I did catch this issue. Now when you come back from background to foreground if you was in the report screen, when the server start the sync again, you can see the correct info.

@Oscar-Pepper if you can test it in your local would be fantastic, since you are who reported it.

### CODE REVIEW

**Comment by juanky201271** [comment]
@zancas I assigned this to you because I don't know who is the perfect reviewer for this...

**Comment by juanky201271** [comment]
@zancas @fluidvanadium @Oscar-Pepper  this is ready for review, I test it, Oscar as well. Thanks in advance.

File: components/SyncReport/SyncReport.tsx [hunk 1]
```diff
@@ -46,6 +46,10 @@ const SyncReport: React.FunctionComponent<SyncReportProps> = ({ closeModal }) =>
   }, [syncingStatusReport.lastBlockServer]);
 
   useEffect(() => {
+    // for some reason when you run the sync process the first block you got (end_block) (yes `end_block`, this is not a mistake)
+    // is one more that the wallet height, if it's the first time you got the wallet birthday + 1
+    // because of that I need, for the math to add 1 in the birthday.
+    // but in the screen I show the real wallet birthday.
```
Comment (Oscar-Pepper) [inline components/SyncReport/SyncReport.tsx:50]: could a transaction be missed in the very first block? if a wallet has a transaction on its birthday when just created?

Comment (juanky201271) [reply components/SyncReport/SyncReport.tsx:50]: As you know, I'm not the best for answering this, but... in my experience, when I create a new wallet always have to sync a number of blocks, I don't remember, maybe 99 blocks or something... said that, It seems improbable that a new wallet have a tx in the first block. But I'm sure that @zancas or @AloeareV have more valid opinions about this.

Comment (zancas) [reply components/SyncReport/SyncReport.tsx:50]: This comment doesn't directly address the question.

If your question is:  "Why does a brand new wallet sync?"
Then this is the answer:

For a brand new wallet the client:
1.  Asks lightwalletd what it believe the [latest tip is](https://github.com/zingolabs/zingo-mobile/blob/da04bb79fcec031a831b3496f33214e34e92cf13/rust/lib/src/lib.rs#L24).
2.  [Subtracts 100 from that](https://github.com/zingolabs/zingo-mobile/blob/da04bb79fcec031a831b3496f33214e34e92cf13/rust/lib/src/lib.rs#L33).
3. Uses [that number](https://github.com/zingolabs/zingo-mobile/blob/da04bb79fcec031a831b3496f33214e34e92cf13/rust/lib/src/lib.rs#L40) as a sync start point for the new wallet it's creating so that it has some buffer in the case of a "reorg" (i.e.  a blockchain split).

I feel uncertain about this architecture, and think it might be vulnerable to a malicious `lightwalletd`.   Am I not _sure_ this is relevant to your question.

Comment (Oscar-Pepper) [reply components/SyncReport/SyncReport.tsx:50]: ok so if we use a <birthday + 1> then there will still be a 99 block buffer?

Comment (juanky201271) [reply components/SyncReport/SyncReport.tsx:50]: I think we are safe then... if I understand well.

Comment (zancas) [reply components/SyncReport/SyncReport.tsx:50]: No, I am sorry I added confusion.   The case that adds 100 blocks is only for a new wallet.

After looking at the `get_birthday` code, I think we need to expose an interface to `zingo-mobile` that gets the actual birthday (if that's what's needed).

Comment (juanky201271) [reply components/SyncReport/SyncReport.tsx:50]: in zingo-mobile I get the birthday from this call: `RPCModule.execute('seed', '');` which have two fields: `seed` & `birthday`...

Comment (juanky201271) [reply components/SyncReport/SyncReport.tsx:50]: But to be clear... I run this: `await RPCModule.execute('sync', '');` no parameters at all... and when I run this: `RPCModule.execute('syncstatus', '');` I noticed that with the first batch info the `end_block` is equal to `birthday + 1`. This info from `syncstatus` doesn't mean nothing wrong with the `sync` process execute before....
This conversation is really interesting but IMO don't have nothing to do with this PR...

**Review by zancas — APPROVED** [review]

**Comment by zancas** [comment]
Hi @fluidvanadium can you merge this?  Does it seem ready to you?

**Comment by zancas** [comment]
It seems to me that this needs a new e2e test demonstrating that the bug is fixed.

**Review by zancas — CHANGES_REQUESTED** [review]
@fluidvanadium can we add an e2e test, showing that this bug is fixed?

**Comment by zancas** [comment]
So this is blocked on test?   I really hope we can get it tested and landed before our release!

**Comment by juanky201271** [comment]
> So this is blocked on test? I really hope we can get it tested and landed before our release!

me too...

**Comment by Oscar-Pepper** [comment]
i am testing again now in emulator... maybe this will be good enough for merge? an e2e would have to be thorough as the bug doesn't always show up so i think manual testing will give us more confidence. an e2e test would still be very valuable though because it would still catch it (eventually) going forward

**Comment by Oscar-Pepper** [comment]
i have tested thoroughly in emulator on two different AVDs and there is no sign of the bug. i think we are good to merge

**Comment by zancas** [comment]
Is it difficult to write an e2e test?

The difference between having an e2e test and not is our awareness about this bug *in the future*.   I believe that this bug is not present now, because of the manual testing.   But..  I assume we're going to change the codebase..  right?   So tomorrow, when the codebase is different, what evidence do we have that the bug is still fixed?

**Comment by juanky201271** [comment]
I added a new test for this bug, but please `test` the new test, since I'm not an expert in e2e detox.

PS: maybe it's necessary a new test to test the new test... I don't know... (I'm joking...)

**Comment by juanky201271** [comment]
The test is in place!

Resultado del test:
C:\Users\juank\github\zingo-mobile-juanky\android>yarn detox test sync_report -c android.emu.debug
yarn run v1.22.15
$ C:\Users\juank\github\zingo-mobile-juanky\node_modules\.bin\detox test sync_report -c android.emu.debug
14:16:27.401 detox[224668] B jest --config e2e/jest.config.js sync_report
14:16:43.435 detox[151124] i sync_report.test.js is assigned to emulator-12536 (Pixel_6_API_30_1)
14:16:51.694 detox[151124] i Renders Sync Report data (blocks & batches) correctly.: loads a wallet
14:17:01.703 detox[151124] i Renders Sync Report data (blocks & batches) correctly.: loads a wallet [OK]
14:17:01.706 detox[151124] i Renders Sync Report data (blocks & batches) correctly.: When App go to background & back to foreground -> Report Screen: blocks & batches are aligned
14:17:45.583 detox[151124] i batches 9
14:17:45.584 detox[151124] i total batches 561
14:17:45.584 detox[151124] i blocks sync now 886
14:17:45.584 detox[151124] i blocks not yet sync 55128
14:17:45.585 detox[151124] i blocks total 56014
14:17:45.586 detox[151124] i Renders Sync Report data (blocks & batches) correctly.: When App go to background & back to foreground -> Report Screen: blocks & batches are aligned [OK]

 PASS  e2e/sync_report.test.js (76.748 s)
  Renders Sync Report data (blocks & batches) correctly.
    √ loads a wallet (10008 ms)
    √ When App go to background & back to foreground -> Report Screen: blocks & batches are aligned (43880 ms)

Done in 79.04s.

**Review by zancas — DISMISSED** [review]

**Comment by zancas** [comment]
Awesome!   I think @fluidvanadium or @Oscar-Pepper or someone with more intimate knowledge of `zingo-mobile` should merge it.

File: e2e/sync_report.test.js [hunk 2]
```diff
@@ -0,0 +1,57 @@
...
+    log.info('batches', batchNum);
+    log.info('total batches', batchesNum);
+    log.info('blocks sync now', blockssyncednowNum);
+    log.info('blocks not yet sync', blocksnotyetsyncedNum);
+    log.info('blocks total', blockstotalNum);
+
+    // a couple of examples:
+    // batch: 1  -> means blocks between 0 and 100
+    // batch: 33 -> means blocks between 3200 and 3300
+    if (blockssyncednowNum < (batchNum * 100) - 100 || blockssyncednowNum > (batchNum * 100)) {
```
Comment (Oscar-Pepper) [inline e2e/sync_report.test.js]: would it be difficult to add a global variable to zingo-mobile called something like `BATCHSIZE` and set it to 100? so if batch size changes we can be confident the code and tests work and also would make it easier as just change one variable

Comment (juanky201271) [reply e2e/sync_report.test.js]: Good idea, actually I can get this value from the screen, like the others values.
For me, the best way to get this value (BATCHSIZE) is from the source (zingolib) and put it in the global context -> this means, you can use it from all/each of the screens, if needed.

Comment (juanky201271) [reply e2e/sync_report.test.js]: I opened this Issue for getting this value from `zingolib` or whatever can be the best idea...
https://github.com/zingolabs/zingo-mobile/issues/285

**Comment by juanky201271** [comment]
New execution of the test:

C:\Users\juank\github\zingo-mobile-juanky\android>yarn detox test sync_report -c android.emu.debug
yarn run v1.22.15
$ C:\Users\juank\github\zingo-mobile-juanky\node_modules\.bin\detox test sync_report -c android.emu.debug
08:16:03.838 detox[275392] B jest --config e2e/jest.config.js sync_report
08:16:21.800 detox[239552] i sync_report.test.js is assigned to emulator-16144 (Pixel_6_API_30_1)
08:16:33.451 detox[239552] i Renders Sync Report data (blocks & batches) correctly.: loads a wallet
08:16:43.978 detox[239552] i Renders Sync Report data (blocks & batches) correctly.: loads a wallet [OK]
08:16:43.985 detox[239552] i Renders Sync Report data (blocks & batches) correctly.: When App go to background & back to foreground -> Report Screen: blocks & batches are aligned
08:17:29.003 detox[239552] i batches 11
08:17:29.003 detox[239552] i total batches 569
08:17:29.004 detox[239552] i blocks sync now 1076
08:17:29.004 detox[239552] i blocks not yet sync 55798
08:17:29.004 detox[239552] i blocks total 56874
08:17:29.005 detox[239552] i batch size: 100
08:17:29.006 detox[239552] i Renders Sync Report data (blocks & batches) correctly.: When App go to background & back to foreground -> Report Screen: blocks & batches are aligned [OK]

 PASS  e2e/sync_report.test.js (83.651 s)
  Renders Sync Report data (blocks & batches) correctly.
    √ loads a wallet (10526 ms)
    √ When App go to background & back to foreground -> Report Screen: blocks & batches are aligned (45021 ms)

Done in 86.24s.

**Review by zancas — APPROVED** [review]
